spring.application.name=sporsalonu
# Web Sunucu Portu
server.port=8080

# MSSQL Veritaban? Ba?lant? Ayarlar?
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SporSalonuDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=alpaslanemin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate (JPA) Ayarlar?
# 'update' kullan?rsak Java, veritaban?nda tablo yoksa kendi açar. Biz tablolar? SQL'de
# elle kurdu?umuz için ve onlara dokunmamas?n? istedi?imiz için 'none' yap?yoruz.

spring.jpa.hibernate.ddl-auto=update

# Arka planda çal??an SQL sorgular?n? konsolda görmek için (Test için harikad?r)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf (HTML Entegrasyonu) Ayarlar?
spring.thymeleaf.cache=false

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
